name: Unpack Incoming UMG Blocks

on:
  push:
    paths:
      - 'incoming_master/**/*.json'

jobs:
  unpack-umg-blocks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if needed)
        run: |
          pip install --upgrade pip

      - name: Run unpack script
        run: |
          python scripts/unpack_umg_blocks.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add public/umg_blocks/**
          git commit -m "Auto-unpack UMG blocks from incoming_master" || echo "No changes to commit"
          git push