name: Run PoeUMG Agent

'on':
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install fastapi uvicorn

      - name: Run PoeUMG Agent Stack
        run: python src/chat_endpoint.py
